apiVersion: v1
kind: LimitRange
metadata:
  name: ex280-limits
  namespace: bluebook
spec:
  limits:
    - type: Pod
      max:
        cpu: 300m
        memory: 300Mi
      min:
        cpu: 100m
        memory: 100Mi
    - type: Container
      max:
        cpu: 300m
        memory: 300Mi
      min:
        cpu: 100m
        memory: 100Mi
      default:
        cpu: 100m
        memory: 100Mi
