apiVersion: v1
kind: LimitRange
metadata:
  name: ex280-quota
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "500m"
        memory: "300Mi"
      min:
        cpu: "10m"
        memory: "100Mi"
    - type: "Container"
      max:
        cpu: "500m"
        memory: "300Mi"
      min:
        cpu: "10m"
        memory: "100Mi"
      defaultRequest:
        cpu: "100m"
        memory: "100Mi"

